### PR TITLE
Update index.js

### PR DESCRIPTION
**Pull request by phenotypic**
1. Reformatted code
2. Changed `config[""]` to `config.`
3. Changed `console.log` to `this.log`
3. Clean up `README.md`

Kinds regards,
Tom

### CODE REVIEW

**Comment by phenotypic** [comment]
Thanks for merging!

Would you be able to push the changes to `npm`?

**Comment by goedh452** [comment]
I’ll do so tomorrow. I’m not at home and don’t have my laptop nearby.

**Comment by phenotypic** [comment]
Okay perfect, thanks

**Comment by goedh452** [comment]
I published the new version to NPM

**Comment by phenotypic** [comment]
My changes don't seem to have been published to `npm`. You can see this if you compare the [README](https://www.npmjs.com/package/homebridge-http-sprinkler) from the `npm` version compared to the [GitHub one](https://github.com/goedh452/homebridge-http-sprinkler#readme) - the same is true for `index.js`. Would you be able to try again and publish these changes?

**Comment by goedh452** [comment]
Sorry, made a stupid mistake :-). Installed it from NPM before publishing instead of Github. I corrected it and created a new version. Now also the release numbers from Github and NPM match.

**Comment by phenotypic** [comment]
Great! All looks good now :)

**Comment by goedh452** [comment]
Hi Tom, I just rolled back some of your changes. You changed "console.log" to "this.console" for outputting messages toe the console, but it was giving me errors and made homebridge crash when I changed the duration time of the sprinkler. The error message was that this.console is not a function.

So I changed it back, published it to NPM and all is fine now :-)

**Comment by phenotypic** [comment]
Ah sorry that's my fault. It should be `this.log` not `this.console`. I'll create a pull request again in a bit unless you want to make the changes?

**Comment by goedh452** [comment]
Sure, I’ll change it to what you suggested! Thanks!

**Comment by goedh452** [comment]
Done!

**Pull request merged**
